### ISSUE TITLE
boolean values used as dropdown argement ids

### ISSUE THREAD

**Issue by irritanterik** [athombv/am.smarter#8] opened 2017-03-26 14:08 UTC
On several cards `true` and `false` are used as value ids. Homey saves the ids after selecting from a dropdown as string values. Matching id's saved in flows with id's in app.json becomes unnecessary complex because of this.

**Comment by RobinBol** [comment] 2017-04-06 12:06
What are you exactly trying to achieve?

**Comment by irritanterik** [comment] 2017-04-06 12:18
Present homey flows with https://github.com/irritanterik/homey-realtime-logpage
For now worked around it with https://github.com/irritanterik/homey-realtime-logpage/commit/ea43c0bd985ca25bb4978d2b33535607021348d3

**Comment by RobinBol** [comment] 2017-04-06 12:20
Ok, but what are you proposing? There is no bug in Homey itself as I read your issue?

**Comment by irritanterik** [comment] 2017-04-06 12:45
In your app.json you define an value id as `true`, but Homey will save it as `'true'`. 
It all works for now, somehow, but its not a great developer experience :).

**Comment by RobinBol** [comment] 2017-04-06 12:56
Yes, it is just a string that is how it is used internally, I don't think this will change to be honest. You might try to change the value to a true boolean value and see if it works?

**Comment by RobinBol** [comment] 2017-09-25 16:22
Will close this issue as it is not a bug, and not related to the Smarter app.

**Closed by RobinBol** 2017-09-25 16:22 UTC
Labels: enhancement
